# Generated by Django 5.0 on 2023-12-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Articles'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Categories'),
        ),
    ]
